Contact header to have private IP on Private cidr
jambonz/sbc-inbound pull request #147
Opened 2024-06-21 04:54 UTC by vdharashive

fix for #146

2024-06-21 11:32 UTC, davehorton commented
what is the scenario here?  How have you tested @vdharashive ?

2024-06-22 02:43 UTC, vdharashive commented
@davehorton if call comes from private network then contact need to have private ips , i have tested this and works fine

2024-06-25 16:30 UTC, davehorton approved these changes

2024-06-25 16:31 UTC, davehorton requested changes
fixing linting errors

2024-06-25 17:41 UTC, davehorton commented on lib/call-session.js
> +      if (isPrivateVoipNetwork(this.req.source_address)) Object.assign(responseHeaders,
sorry to be picky but could you make this
```
if (isPrivateVoipNetwork(this.req.source_address)) {
   Object.assign( responseHeaders, {'Contact': `<sip:${this.privateSipAddress}>`});
}
```

2024-06-25 18:33 UTC, davehorton approved these changes

2024-06-25 18:34 UTC, merged